#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 8b93847
#
Name     : libpinyin
Version  : 2.10.0
Release  : 23
URL      : https://sourceforge.net/projects/libpinyin/files/libpinyin/libpinyin-2.10.0.tar.gz
Source0  : https://sourceforge.net/projects/libpinyin/files/libpinyin/libpinyin-2.10.0.tar.gz
Summary  : Library to deal with pinyin
Group    : Development/Tools
License  : GPL-3.0
Requires: libpinyin-bin = %{version}-%{release}
Requires: libpinyin-lib = %{version}-%{release}
Requires: libpinyin-license = %{version}-%{release}
Requires: libpinyin-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : kyotocabinet-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(kyotocabinet)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libpinyin
Library to deal with pinyin.
The libpinyin project aims to provide the algorithms core for intelligent sentence-based Chinese pinyin input methods.

%package bin
Summary: bin components for the libpinyin package.
Group: Binaries
Requires: libpinyin-license = %{version}-%{release}

%description bin
bin components for the libpinyin package.


%package dev
Summary: dev components for the libpinyin package.
Group: Development
Requires: libpinyin-lib = %{version}-%{release}
Requires: libpinyin-bin = %{version}-%{release}
Provides: libpinyin-devel = %{version}-%{release}
Requires: libpinyin = %{version}-%{release}

%description dev
dev components for the libpinyin package.


%package lib
Summary: lib components for the libpinyin package.
Group: Libraries
Requires: libpinyin-license = %{version}-%{release}

%description lib
lib components for the libpinyin package.


%package license
Summary: license components for the libpinyin package.
Group: Default

%description license
license components for the libpinyin package.


%package man
Summary: man components for the libpinyin package.
Group: Default

%description man
man components for the libpinyin package.


%prep
%setup -q -n libpinyin-2.10.0
cd %{_builddir}/libpinyin-2.10.0
pushd ..
cp -a libpinyin-2.10.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739156510
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-dbm=KyotoCabinet
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-dbm=KyotoCabinet
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1739156510
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libpinyin
cp %{_builddir}/libpinyin-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libpinyin/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/libpinyin/data/addon_phrase_index.bin
/usr/lib64/libpinyin/data/addon_pinyin_index.bin
/usr/lib64/libpinyin/data/art.bin
/usr/lib64/libpinyin/data/bigram.db
/usr/lib64/libpinyin/data/culture.bin
/usr/lib64/libpinyin/data/economy.bin
/usr/lib64/libpinyin/data/gb_char.bin
/usr/lib64/libpinyin/data/gbk_char.bin
/usr/lib64/libpinyin/data/geology.bin
/usr/lib64/libpinyin/data/history.bin
/usr/lib64/libpinyin/data/life.bin
/usr/lib64/libpinyin/data/merged.bin
/usr/lib64/libpinyin/data/nature.bin
/usr/lib64/libpinyin/data/opengram.bin
/usr/lib64/libpinyin/data/people.bin
/usr/lib64/libpinyin/data/phrase_index.bin
/usr/lib64/libpinyin/data/pinyin_index.bin
/usr/lib64/libpinyin/data/punct.bin
/usr/lib64/libpinyin/data/science.bin
/usr/lib64/libpinyin/data/society.bin
/usr/lib64/libpinyin/data/sport.bin
/usr/lib64/libpinyin/data/table.conf
/usr/lib64/libpinyin/data/technology.bin

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gen_binary_files
/V3/usr/bin/gen_unigram
/V3/usr/bin/import_interpolation
/usr/bin/gen_binary_files
/usr/bin/gen_unigram
/usr/bin/import_interpolation

%files dev
%defattr(-,root,root,-)
/usr/include/libpinyin-2.10.0/novel_types.h
/usr/include/libpinyin-2.10.0/pinyin.h
/usr/include/libpinyin-2.10.0/pinyin_custom2.h
/usr/lib64/libpinyin.so
/usr/lib64/pkgconfig/libpinyin.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libpinyin.so.15.0.0
/usr/lib64/libpinyin.so.15
/usr/lib64/libpinyin.so.15.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libpinyin/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/libpinyin.1
